### ISSUE TITLE
Open dashboard not working for AKS 1.4+

### ISSUE THREAD

**Issue by dfgrosso** [Azure/vscode-kubernetes-tools#617]
Issue Type: <b>Bug</b>

Greetings.

I´ve been using this extension to open the dashboard on my Azure AKS cluster. It's been working fine but once I've upgrade the AKS to version 1.14 e stopped working. I'm getting this error:

 kubectl proxy | tee c:\Users\daniel.grosso\.vscode\extensions\ms-kubernetes-tools.vscode-kubernetes-tools-1.0.4\out\src\components\kubectl\proxy.out
out-file : The process cannot access the file 'C:\Users\daniel.grosso\.vscode\extensions\ms-kubernetes-tools.vscode-kubernetes-tools-1.0.4\out\src\components\kubectl\proxy.out' because it is being used by another process.
At line:1 char:1
+ kubectl proxy | tee c:\Users\daniel.grosso\.vscode\extensions\ms-kube ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [out-file], IOException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

Extension version: 1.0.4
VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (5.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cforce** [comment]
same heree:

```
> kubectl proxy | tee c:\Users\user\.vscode\extensions\ms-kubernetes-tools.vscode-kubernetes-tools-1.0.4\out\src\components\kubectl\proxy.out
out-file : Der Prozess kann nicht auf die Datei "C:\Users\fwallwit\.vscode\extensions\ms-kubernetes-tools.vscode-kube
rnetes-tools-1.0.4\out\src\components\kubectl\proxy.out" zugreifen, da sie von einem anderen Prozess verwendet wird.
In Zeile:1 Zeichen:1
+ kubectl proxy | tee c:\Users\fwallwit\.vscode\extensions\ms-kubernete ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [out-file], IOException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
```

**Comment by ifridemberg** [comment]
same here

**Comment by ugumba** [comment]
Likewise!  

Also, after trying a couple of times (and closing some Powershell terminals), I end up with this popup message instead:
```Something went wrong when ensuring the Kubernetes API Proxy output stream existed```
Restarting VSCode gets rid of that, and brings back "The process cannot access the file ...".

"kubectl proxy" works as normal, but i was hoping the extension would be able to deduce the correct Dashboard URL for me, as I switch between multiple clusters (local, AKS and GCP), with different dashboard namespaces etc.

**Comment by itowlson** [comment]
Sorry for the delay on replying to this - I've been away.  I see @bnookala is planning to pick this up.

**Comment by itowlson** [comment]
@bnookala do you have any bandwidth to look at this?

**Comment by Sensarg22** [comment]
same here

**Comment by KristofKlein** [comment]
same here

**Comment by itowlson** [comment]
@bnookala do you have bandwidth for this?

**Comment by itowlson** [comment]
cc @Tatsinnit

**Comment by Tatsinnit** [comment]
⛩️ 👍 Cool, Yeah, I will start playing with this one today or tomorrow. I have not spend time in this extension but will be fun to dig deeper in this, will loop back **or** defo DM you as well to get the whole things more clear or lets ping-pong on teams anyways when you are free. Thank you :)  (Feel free to assign it to me)

**Comment by Tatsinnit** [comment]
🏗️ 💡 :  **Working at this end with minor delay** Had a quick play around and though I will loop back for a behaviour I notice. It seems like there is a visible delay of some sort essentially it will consistently start working once you have fist time load resolved:

📓 For folks who might have consistent failure: it might be worth to describe exact replication along with the permission level which might help in understanding in more detail **Or** I am sure folk s who know more around this extension will add extra but seems to be working at this end (delay was the only visible issue which shows browser level error uploading page - but in 10 seconds or so everything loaded).

Screenshot and how it seems to be behaving: (Please note obviously I built it form the code but I think it will be same experience for the end user)

* Set a cluster to the "Current Cluster context"
* Right click: select "Open DashBoard" 
* first time, it took atleast 10 to 15 second delay to load but when I was finished I was able to **successfully** see dashboard successfully.

Command prompt and 

<img width="1267" alt="Screen Shot 2020-06-08 at 9 48 39 AM" src="https://user-images.githubusercontent.com/6233295/83980926-88ceb900-a96d-11ea-925d-e4bca8a63472.png">


**Working Screenshot** 

<img width="1750" alt="Screen Shot 2020-06-08 at 9 39 52 AM 2" src="https://user-images.githubusercontent.com/6233295/83980868-2d043000-a96d-11ea-99b0-ee72a8eac1f3.png">


cc: @bnookala +  @itowlson

**Comment by itowlson** [comment]
I'm seeing the same thing - dashboard comes up but the dashboard account doesn't have permissions. So different symptoms... but the result is the same from the user's point of view.  How does `az aks dashboard` do this?  Should we call `az aks dashboard` instead of using the port forwarding approach?  @bnookala

**Comment by itowlson** [comment]
Correction: `az aks browse` not `dashboard`.

**Comment by bnookala** [comment]
> But we're getting enough reports that not _all_ our users can be mistaken about whether they have an AKS cluster. Could it be that we're not detecting whether a cluster is AKS? We've seen some oddities in telemetry around AKS detection too (cc @squillace)..
> 

yeah, I'm curious if the annotations that we select for to determine if the cluster is AKS has changed as well - [this](https://github.com/Azure/vscode-kubernetes-tools/blob/29e59d593118e081cddd3559d9f16118ea378f01/src/components/kubectl/dashboard.ts#L52) would be a good starting point.

**Comment by Tatsinnit** [comment]
💡 interesting: It's similar behaviour for `az aks browse` for me: Screenshot below:

cc: @itowlson 

<img width="1656" alt="Screen Shot 2020-06-15 at 12 42 27 PM" src="https://user-images.githubusercontent.com/6233295/84608305-e763dc00-af05-11ea-97a7-d51f6df2aae6.png">

**Comment by itowlson** [comment]
I guess this is working as well as the AKS dashboard allows then.  Folks who have confirmed this bug - is it still happening for you?  Do you get the orange permissions screen?  Or nothing at all?

@Tatsinnit off topic for the k8s extension, but it might be good to talk to the AKS folks and find out if the orange permissions screen is 'working as designed' or if something is awry...

**Comment by Tatsinnit** [comment]
Sounds good and here is quick update: I have found something interesting mentioned in `az aks` behavior. 🦺 Beside other confirmation from OP for extension side of things, **re**: `az aks browse` command 💡 This behavior looks very similar to this here: https://github.com/Azure/AKS/issues/601  , hence I have reached out to the folks for confirmation. thanks.  cc \ fyi: @itowlson

**Comment by Tatsinnit** [comment]
Loop back from what I have found.

* 💡 Follow up from "off-topic" conversation around the `az aks` side of behavior as mentioned above, just to keep the thread updated: The `az cli` experience \ workflow is different and the orange permissions is resolved via : https://github.com/Azure/AKS/issues/601#issuecomment-552020383 or https://docs.microsoft.com/en-us/azure/aks/kubernetes-dashboard#sign-in-to-the-dashboard-kubernetes-116 

* Again off topic form the original issue: At the screen at-least from the `vscode` point  or view the orange screen with permission thing is something can only be explained if anyone has clarity if this is to do something with the permission model residing underneath or is it as simple as running as `<some diff permission role>` i.e. `cluster-admin` or something.

**Comment by IAmHopp** [comment]
Guys, I'm bumping this up because, although I see the conversation evolved a lot from the original issue mentioned, I still get that same behavior. Meaning, I get this error message when I click on Open Dashboard:

> out-file : Access to the path 'C:\Users\<myuser>\.vscode-insiders\extensions\ms-kubernetes-tools.vscode-kubernetes-tools-1.3.3\dist\proxy.out' is denied.

**Comment by squillace** [comment]
@IAmHopp apologies but this is not a VS Code Kubernetes extension issue -- unfortunately. AKS changed the security stance of the Kube dashboard, and for good reason. It turns out that an available dashboard is the main single security weakness for exploiting clusters across all clouds, and I'm fairly sure that no cloud now enables it by default (if they do, it's a vector).

We do need documentation for this in the azure documents -- but not specifically the vs code extension documents, as the issue and how to resolve it vary by distribution (that is, how you get this to work on other clouds varies). The workaround is here: https://github.com/Azure/vscode-kubernetes-tools/issues/617#issuecomment-662206061 

We'll continue to look at a general solution to the problem. But the issue itself is by design on the AKS side.

**Comment by IAmHopp** [comment]
I see. I just wonder if there isn't a way to better communicate this to the end user? The error message I get seems to not be descriptive of the actual issue at all. It seems to be a basic file permission error. If it goes any deeper than that, I think that should be communicated to the end user, if possible.

FYI I'm not using AKS. (: I don't think the workaround applies for me at all. I'm not getting permission errors from the opened dashboard. I can't open the dashboard at all because all I get is an error in the terminal.

**Comment by squillace** [comment]
yes, we'll work on a general "fix" -- which is almost certainly going to be a better error message pointing out the general problem. But note, because all we're doing is what can be done on the command line, quite literally one fix could be, "if you can't run <command> on the command line, VS Code can't do it either. Go fix it." :-)

You should also remember that other than trying to figure out whether it's an azure cluster (which is guesswork, really) we don't sniff your cluster info to find out where you're running against (and you can turn off telemetry completely!) so there's no way for us to know why you can't open the dashboard, ultimately. But we CAN try to help you diagnose it. :-|

**Comment by IAmHopp** [comment]
>But note, because all we're doing is what can be done on the command line, quite literally one fix could be, "if you can't run on the command line, VS Code can't do it either. Go fix it." :-)

I get it if you're talking about the Kubernetes commands themselves. But kubectl proxy (which is the Kubernetes part of the command Visual Studio Code is issuing) works fine here from the command line. (:

The error is an access denied on the file inside the folder of the extension. That's where I think either we're not speaking about the same thing, or I'm missing something from what you're saying. It's fine if the extension can't open the dashboard for whatever reason, but the error message is regarding a file from the extension folder.

Either way... If you're sure it's expected behavior, I'm fine with a better error message, like you said. That'd already be an improved user experience IMO. (:

**Comment by squillace** [comment]
> The error is an access denied on the file inside the folder of the extension. 

THAT we'll be sure to understand and fix, IF possible. Note that now VS Code has changed its behavior to require trusting of certain extension resources -- so we now have a larger issue to address that may or may NOT be related to what you're seeing here. :-|

Life is fun.

**Comment by IAmHopp** [comment]
>THAT we'll be sure to understand and fix, IF possible.

Perfect. All I was asking. (:
